### ISSUE TITLE
Could not parse item

### ISSUE THREAD

**Issue by cpursley** [oltarasenko/products-advisor#2]
I'm getting an error that looks like this:

```
iex(1)> Crawly.Engine.start_spider(Homebase)

20:56:45.680 [info]  Starting the manager for Elixir.Homebase
 
20:56:45.695 [debug] Starting requests storage worker for Elixir.Homebase...
 
20:56:47.445 [debug] Started 16 workers for Elixir.Homebase
:ok
iex(2)> 
20:56:48.667 [info]  Dropping item: %{category: "Tools", description: "", id: "", images: [], title: ""}. Reason: missing required fields
 
20:56:50.085 [info]  Dropping item: %{category: "Lighting & Electrical", description: "", id: "", images: [], title: ""}. Reason: missing required fields 
 
20:56:51.606 [error] Could not parse item, error: :error, reason: :undef, stacktrace: [{ExMagic, :from_buffer!, [<<255, 216, 255, 224, 0, 16, 74, 70, 73, 70, 0, 1, 1, 1, 0, 96, 0, 96, 0, 0, 255, 219, 0, 67, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...>>], []}, {ProductsAdvisor.Spider, :save_jpeg, 2, [file: 'lib/products_advisor/spider.ex', line: 21]}, {Enum, :"-each/2-lists^foreach/1-0-", 2, [file: 'lib/enum.ex', line: 769]}, {Enum, :each, 2, [file: 'lib/enum.ex', line: 769]}, {Homebase, :parse_item, 1, [file: 'lib/products_advisor/spider/homebase.ex', line: 65]}, {Crawly.Worker, :parse_item, 1, [file: 'lib/crawly/worker.ex', line: 76]}, {:epipe, :run, 2, [file: '/Users/cpursley/Development/learning/scrape/products-advisor/deps/epipe/src/epipe.erl', line: 23]}, {Crawly.Worker, :handle_info, 2, [file: 'lib/crawly/worker.ex', line: 43]}]
          
 
20:56:51.606 [warn]  The on_load function for module Elixir.ExMagic returned:
{{:badmatch, {:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/priv/exmagic.so, 2): image not found\''}}}, [{ExMagic, :init, 0, [file: 'lib/exmagic.ex', line: 15]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, [file: 'code_server.erl', line: 1340]}]}

 
20:56:51.612 [error] Process #PID<0.424.0> raised an exception
** (MatchError) no match of right hand side value: {:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/priv/exmagic.so, 2): image not found\''}}
    (exmagic) lib/exmagic.ex:15: ExMagic.init/0
    (kernel) code_server.erl:1340: anonymous fn/1 in :code_server.handle_on_load/5
 
20:56:51.938 [error] Process #PID<0.426.0> raised an exception
** (MatchError) no match of right hand side value: {:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/priv/exmagic.so, 2): image not found\''}}
    (exmagic) lib/exmagic.ex:15: ExMagic.init/0
    (kernel) code_server.erl:1340: anonymous fn/1 in :code_server.handle_on_load/5
 
20:56:51.940 [error] Could not parse item, error: :error, reason: :undef, stacktrace: [{ExMagic, :from_buffer!, [<<255, 216, 255, 224, 0, 16, 74, 70, 73, 70, 0, 1, 1, 1, 0, 96, 0, 96, 0, 0, 255, 219, 0, 67, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...>>], []}, {ProductsAdvisor.Spider, :save_jpeg, 2, [file: 'lib/products_advisor/spider.ex', line: 21]}, {Enum, :"-each/2-lists^foreach/1-0-", 2, [file: 'lib/enum.ex', line: 769]}, {Enum, :each, 2, [file: 'lib/enum.ex', line: 769]}, {Homebase, :parse_item, 1, [file: 'lib/products_advisor/spider/homebase.ex', line: 65]}, {Crawly.Worker, :parse_item, 1, [file: 'lib/crawly/worker.ex', line: 76]}, {:epipe, :run, 2, [file: '/Users/cpursley/Development/learning/scrape/products-advisor/deps/epipe/src/epipe.erl', line: 23]}, {Crawly.Worker, :handle_info, 2, [file: 'lib/crawly/worker.ex', line: 43]}]
          
```

**Comment by velimir** [comment]
stacktrace says that `ExMagic.init/0` failed to load NIF library:
> dlopen(/Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/priv/exmagic.so, 2)

It could be that `ExMagic` was not successfuly compiled.

Could you share compilation log? What platform you are tying to compile this project on?

**Comment by cpursley** [comment]
- macOS 10.13.6
- Elixir 1.8.1

```
$ mix deps.get
* Getting exmagic (https://github.com/andrew-d/exmagic.git)
remote: Enumerating objects: 143, done.        
remote: Total 143 (delta 0), reused 0 (delta 0), pack-reused 143        
Receiving objects: 100% (143/143), 230.99 KiB | 2.29 MiB/s, done.
Resolving deltas: 100% (68/68), done.
warning: String.strip/1 is deprecated. Use String.trim/1 instead
  /Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/mix.exs:66

warning: module attribute @shortdoc was set but never used
  /Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/mix.exs:75

warning: module attribute @shortdoc was set but never used
  /Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/mix.exs:90

* Getting libmagic (https://github.com/file/file)
remote: Enumerating objects: 79, done.        
remote: Counting objects: 100% (79/79), done.        
remote: Compressing objects: 100% (52/52), done.        
remote: Total 29589 (delta 39), reused 52 (delta 27), pack-reused 29510        
Receiving objects: 100% (29589/29589), 7.65 MiB | 3.62 MiB/s, done.
Resolving deltas: 100% (21120/21120), done.
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  certifi 2.5.1
  cowboy 2.6.3
  cowlib 2.7.3
  crawly 0.1.0
  epipe 1.0.0
  floki 0.20.4
  hackney 1.15.1
  html_entities 0.4.0
  httpoison 1.5.1
  idna 6.0.0
  metrics 1.0.1
  mime 1.3.1
  mimerl 1.2.0
  mochiweb 2.18.0
  new_gollum 0.3.0
  parse_trans 3.3.0
  plug 1.8.0
  plug_cowboy 2.0.2
  plug_crypto 1.0.0
  poison 3.1.0
  ranch 1.7.1
  ssl_verify_fun 1.1.4
  unicode_util_compat 0.4.1
  uuid 1.1.8
* Getting crawly (Hex package)
* Getting epipe (Hex package)
* Getting floki (Hex package)
* Getting httpoison (Hex package)
* Getting new_gollum (Hex package)
* Getting plug_cowboy (Hex package)
* Getting poison (Hex package)
* Getting uuid (Hex package)
* Getting cowboy (Hex package)
* Getting plug (Hex package)
* Getting mime (Hex package)
* Getting plug_crypto (Hex package)
* Getting cowlib (Hex package)
* Getting ranch (Hex package)
* Getting hackney (Hex package)
* Getting certifi (Hex package)
* Getting idna (Hex package)
* Getting metrics (Hex package)
* Getting mimerl (Hex package)
* Getting ssl_verify_fun (Hex package)
* Getting unicode_util_compat (Hex package)
* Getting parse_trans (Hex package)
* Getting html_entities (Hex package)
* Getting mochiweb (Hex package)
```

**Comment by cpursley** [comment]
```
$ iex -S mix
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

warning: String.strip/1 is deprecated. Use String.trim/1 instead
  /Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/mix.exs:66

warning: module attribute @shortdoc was set but never used
  /Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/mix.exs:75

warning: module attribute @shortdoc was set but never used
  /Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/mix.exs:90

===> Compiling parse_trans
===> Compiling mimerl
==> exmagic
mkdir -p priv
cd ../libmagic && autoreconf -i
/bin/sh: autoreconf: command not found
make: *** [priv/libmagic-5.29.stamp] Error 127

Compiling 1 file (.ex)
Generated exmagic app

13:10:53.195 [warn]  The on_load function for module Elixir.ExMagic returned:
{{:badmatch, {:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/priv/exmagic.so, 2): image not found\''}}}, [{ExMagic, :init, 0, [file: 'lib/exmagic.ex', line: 15]}, {:code_server, :"-handle_on_load/5-fun-0-", 1, [file: 'code_server.erl', line: 1340]}]}

 
13:10:53.199 [error] Process #PID<0.179.0> raised an exception
** (MatchError) no match of right hand side value: {:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/cpursley/Development/learning/scrape/products-advisor/deps/exmagic/priv/exmagic.so, 2): image not found\''}}
    lib/exmagic.ex:15: ExMagic.init/0
    (kernel) code_server.erl:1340: anonymous fn/1 in :code_server.handle_on_load/5
===> Compiling metrics
===> Compiling unicode_util_compat
===> Compiling idna
===> Compiling ranch
warning: String.strip/1 is deprecated. Use String.trim/1 instead
  /Users/cpursley/Development/learning/scrape/products-advisor/deps/poison/mix.exs:4

==> poison
Compiling 4 files (.ex)
warning: Integer.to_char_list/2 is deprecated. Use Integer.to_charlist/2 instead
  lib/poison/encoder.ex:173

Generated poison app
==> ssl_verify_fun
Compiling 7 files (.erl)
Generated ssl_verify_fun app
==> html_entities
Compiling 2 files (.ex)
Generated html_entities app
===> Fetching rebar3_hex ({pkg,<<"rebar3_hex">>,<<"6.8.0">>})
===> Version cached at /Users/cpursley/.cache/rebar3/hex/default/packages/rebar3_hex-6.8.0.tar is up to date, reusing it
===> Fetching hex_core ({pkg,<<"hex_core">>,<<"0.5.0">>})
===> Version cached at /Users/cpursley/.cache/rebar3/hex/default/packages/hex_core-0.5.0.tar is up to date, reusing it
===> Fetching verl ({pkg,<<"verl">>,<<"1.0.1">>})
===> Version cached at /Users/cpursley/.cache/rebar3/hex/default/packages/verl-1.0.1.tar is up to date, reusing it
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
===> Compiling epipe
===> Compiling certifi
===> Compiling hackney
==> httpoison
Compiling 3 files (.ex)
Generated httpoison app
==> new_gollum
Compiling 6 files (.ex)
warning: function init/1 required by behaviour GenServer is not implemented (in module Gollum.Cache).

We will inject a default implementation for now:

    def init(init_arg) do
      {:ok, init_arg}
    end

You can copy the implementation above or define your own that converts the arguments given to GenServer.start_link/3 to the server state.

  lib/gollum/cache.ex:1

Generated new_gollum app
===> Compiling cowlib
===> Compiling cowboy
===> Compiling mochiweb
src/mochiweb_socket.erl:91: Warning: ssl:ssl_accept/2: deprecated; use ssl:handshake/2 instead

==> floki
Compiling 1 file (.xrl)
Compiling 1 file (.erl)
Compiling 21 files (.ex)
Generated floki app
==> uuid
Compiling 1 file (.ex)
Generated uuid app
==> mime
Compiling 2 files (.ex)
Generated mime app
==> plug_crypto
Compiling 4 files (.ex)
Generated plug_crypto app
==> plug
Compiling 1 file (.erl)
Compiling 39 files (.ex)
warning: System.stacktrace/0 outside of rescue/catch clauses is deprecated. If you want to support only Elixir v1.7+, you must access __STACKTRACE__ inside a rescue/catch. If you want to support earlier Elixir versions, move System.stacktrace/0 inside a rescue/catch
  lib/plug/conn/wrapper_error.ex:23

warning: function :telemetry.execute/3 is undefined (module :telemetry is not available)
Found at 2 locations:
  lib/plug/telemetry.ex:70
  lib/plug/telemetry.ex:74

Generated plug app
==> plug_cowboy
Compiling 5 files (.ex)
Generated plug_cowboy app
==> crawly
Compiling 24 files (.ex)
Generated crawly app
==> products_advisor
Compiling 5 files (.ex)
Generated products_advisor app

13:11:16.923 [info]  Starting data storage
Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
```

**Comment by velimir** [comment]
`exmagic` was not compiled as `autoconf` couldn't be found:

```
==> exmagic
mkdir -p priv
cd ../libmagic && autoreconf -i
/bin/sh: autoreconf: command not found
make: *** [priv/libmagic-5.29.stamp] Error 127
```

You can install it from `brew`:

```
$ brew install autoconf
```

**Comment by velimir** [comment]
Closing as non products advisor issue.

**Comment by cpursley** [comment]
I recommend mentioning in the README that `autoreconf` is a dependency which must be installed. Thank you.
